In [1]:
import numpy as np

In [2]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [4]:
np.linspace(0, 10, 0.2)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  """Entry point for launching an IPython kernel.


array([], dtype=float64)

In [5]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.random.rand(5)

array([0.16049444, 0.42927776, 0.66618776, 0.06943246, 0.46618473])

In [8]:
np.random.rand(5,5)

array([[0.08154793, 0.43208641, 0.0610613 , 0.73052931, 0.90535665],
       [0.72339941, 0.55343541, 0.90776359, 0.61253689, 0.53014721],
       [0.03789593, 0.40187978, 0.68106684, 0.94332011, 0.64594829],
       [0.98035973, 0.67956657, 0.06926455, 0.59799844, 0.2016523 ],
       [0.52223159, 0.50508927, 0.13023932, 0.43335566, 0.2444046 ]])

In [9]:
np.random.randn(2)

array([-0.20344225, -0.58897128])

In [10]:
np.random.randn(20)

array([ 1.74041571,  0.03592114,  0.35914346,  0.82679177,  1.78957311,
       -0.21634004, -1.42415464, -0.71103523, -0.8148939 , -0.33487226,
       -0.05899515, -0.84512682,  1.93221555,  0.88219802, -0.64099986,
        0.01633988, -0.23307745,  0.31233423,  0.71225511,  0.24819031])

In [11]:
np.random.randn(4,4)

array([[-0.23354366, -0.53789619,  0.32087549,  1.39934407],
       [ 0.70978456, -0.9051121 ,  1.36846652, -0.3590416 ],
       [ 1.41446785,  0.24299631,  0.61393451,  1.30728301],
       [-0.85953145,  0.35766044,  1.46383243,  0.65426604]])

In [12]:
np.random.randint(1, 100, 10)

array([81, 23, 36, 39, 85, 45, 19, 65, 20, 33])

In [13]:
arr = np.arange(25)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
ranarr = np.random.randint(0, 50, 10)

In [16]:
ranarr

array([14, 23, 18,  5, 21, 42, 14, 47,  0, 32])

In [17]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
ranarr.max()

47

In [19]:
ranarr.min()

0

In [20]:
ranarr

array([14, 23, 18,  5, 21, 42, 14, 47,  0, 32])

In [21]:
ranarr.argmax()

7

In [22]:
ranarr.argmin()

8

In [23]:
arr.shape()

TypeError: 'tuple' object is not callable

In [24]:
arr.shape

(25,)

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arr.shape

(25,)

In [27]:
arr.dtype

dtype('int32')

In [28]:
ranarr.dtype

dtype('int32')

In [1]:
from numpy.random import randint

In [2]:
randint(2,10)

2